//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Car = new HashSet<Car>();
        }
    
        public System.Guid AccountId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual Role Role { get; set; }
    }
}
