//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public System.Guid CarId { get; set; }
        public string License { get; set; }
        public System.Guid AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
