//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int RoleId { get; set; }
        public string Symbol { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
    }
}
